// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8pHcU10Eazon9uzsAi2HR2KUukGz7kFw',
    appId: '1:887097222119:web:cadde7db16c3a363ec9342',
    messagingSenderId: '887097222119',
    projectId: 'project-myapp-d2142',
    authDomain: 'project-myapp-d2142.firebaseapp.com',
    storageBucket: 'project-myapp-d2142.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCO8-Qfj-jrKiPWjsCfPKipMYfJDhYfAhI',
    appId: '1:887097222119:android:19d41c2b1f91aac4ec9342',
    messagingSenderId: '887097222119',
    projectId: 'project-myapp-d2142',
    storageBucket: 'project-myapp-d2142.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTD6GPxM4T9bpOsinI89JwT29NyLywDeg',
    appId: '1:887097222119:ios:71bb4f53962878ffec9342',
    messagingSenderId: '887097222119',
    projectId: 'project-myapp-d2142',
    storageBucket: 'project-myapp-d2142.firebasestorage.app',
    iosBundleId: 'com.example.projectMyapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTD6GPxM4T9bpOsinI89JwT29NyLywDeg',
    appId: '1:887097222119:ios:71bb4f53962878ffec9342',
    messagingSenderId: '887097222119',
    projectId: 'project-myapp-d2142',
    storageBucket: 'project-myapp-d2142.firebasestorage.app',
    iosBundleId: 'com.example.projectMyapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8pHcU10Eazon9uzsAi2HR2KUukGz7kFw',
    appId: '1:887097222119:web:29bd418b31aafc17ec9342',
    messagingSenderId: '887097222119',
    projectId: 'project-myapp-d2142',
    authDomain: 'project-myapp-d2142.firebaseapp.com',
    storageBucket: 'project-myapp-d2142.firebasestorage.app',
  );
}
